version: '3'

services:

  ## --------------------------------------------
  ## | 1: python 3.7
  ## --------------------------------------------
  andi_python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis
